services:
  fntv-iptv-proxy:
    image: chanhuan01/fntv-iptv-proxy:latest
    container_name: fntv-iptv-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./iptv_channels.m3u:/app/iptv_channels.m3u:ro
